import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
} from '@clerk/nextjs'
import Provider from "./provider";
import { Toaster } from "sonner";
const AppFont = DM_Sans({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Ai video Course Generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${AppFont.className}`}
      >
        <Provider>
          {children}
          <Toaster position="top-center" richColors/>
        </Provider>
      </body>
    </html>
    </ClerkProvider>
  );
}
